### ISSUE TITLE
Docker image appears broken

### ISSUE THREAD

**Issue by stevengorrell** [rackerlabs/tuvok#27]
##### Summary
Docker container does not seem to be working.

```
➜  tuvok git:(master) docker build -t tuvok-image .
Sending build context to Docker daemon  829.4kB
Step 1/9 : FROM amazonlinux:2.0.20180622.1
2.0.20180622.1: Pulling from library/amazonlinux
638b75f800bf: Already exists 
Digest: sha256:802212e258f7b67b5754c795f17395937918b29629dd72af615b768f0fcb6cf3
Status: Downloaded newer image for amazonlinux:2.0.20180622.1
 ---> 585cc50169e6
Step 2/9 : LABEL maintainer="Rackspace"
 ---> Running in 1bb761c5137d
Removing intermediate container 1bb761c5137d
 ---> 3d792f7eed70
Step 3/9 : ENV APP_HOME /tuvok
 ---> Running in a9b1e96c9d11
Removing intermediate container a9b1e96c9d11
<<<TRUNCATED>>>
Step 9/9 : ENTRYPOINT [ "python3", "tuvok/tuvok/cli.py" ]
 ---> Running in 069beba0e1d9
Removing intermediate container 069beba0e1d9
 ---> ae59c7cff2a7
Successfully built ae59c7cff2a7
```

```
➜  tuvok git:(master) docker image ls
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
tuvok-image         latest              ae59c7cff2a7        2 minutes ago       656MB
hello-world         latest              4ab4c602aa5e        2 months ago        1.84kB
amazonlinux         2.0.20180622.1      585cc50169e6        4 months ago        163MB
```

```
➜  tuvok git:(master) docker run tuvok-image 
Traceback (most recent call last):
  File "tuvok/tuvok/cli.py", line 9, in <module>
    from tuvok import __version__
  File "/tuvok/tuvok/tuvok.py", line 1, in <module>
    from tuvok.plugins import BaseTuvokPlugin
ModuleNotFoundError: No module named 'tuvok.plugins'; 'tuvok' is not a package
➜  tuvok git:(master)
```

##### Expected Behavior:

Container should launch without error.

##### Actual Behavior:

Container errors out on launch.

##### Steps to Reproduce:

See summary.

##### Additional Details:
Ubuntu 16.04 LTS

```
➜  tuvok git:(master) docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:57 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by martinb3** [comment]
This should be resolved with #28. I confirmed with @stevengorrell 👍
